### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by maiersoft** [migueldeicaza/TweetStation#8]
With the app available from AppStore i cannot login into my twitter account.
Don't know if it's a network problem or some authentication problem with the twitter API...

**Comment by migueldeicaza** [comment]
I got a fix on the pipeline, waiting for Apple's approval.

For now, do this: enter your login, your password, and before you click "Login", tap the username field again to edit it, then tap the button. 

It was a bug in my route to fetch the password, I apologize

**Comment by maiersoft** [comment]
Hey Miguel,
absolutely no need to apologize! :)
This code is incredibly useful. Thanks so much!
